### ISSUE TITLE
nv migrate fails

### ISSUE THREAD

**Issue by BenNG** [christiansmith/anvil-connect#73]
Hi. This error appears in 0.1.27 and is not in 0.1.26
Here is the logs

$ nv migrate
Error: Cannot find module '../../config/redis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/benng/bin/anvil-connect-0.1.27/lib/cli/migrate.js:7:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Usage: nv [--version] [--help] <command> [<args>]

**Comment by christiansmith** [comment]
Thanks for catching this! Just released a fix in 0.1.28. Please let me know if you run into any further issues.
